name: LTS

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    # manual trigger
  schedule:
    - cron: '0 0 * * 0' # weekly

jobs:
  build-lts:
    uses: ./.github/workflows/build-core.yml
    with:
      branch: LTS
      version_suffix: lts